#!/usr/bin/env bash
# deploy.sh — Full deployment for icd10-gapanalysis-demo
#
# databricks.yml is the single source of truth for all config variables.
# This script reads defaults from databricks.yml — no values are hardcoded here.
# Command-line flags override those defaults when provided.
#
# Sequence:
#   1. Read variable defaults from databricks.yml
#   2. setup_resources.py  — resolve / create SQL warehouse + KA endpoint
#   3. Generate app.yaml   — write all env vars from resolved values
#   4. Deploy app          — establishes app service principal
#   5. Grant permissions   — warehouse CAN_USE + KA endpoint CAN_QUERY to app SP
#   6. Bundle deploy       — creates Jobs with all vars from single source
#
# Usage:
#   ./deploy.sh --app-path <workspace-path-to-app-dir> [overrides]
#
# Overrides (all optional — defaults come from databricks.yml):
#   --profile           Databricks CLI profile
#   --catalog           Unity Catalog name
#   --schema            Schema name
#   --warehouse-id      SQL warehouse ID         (auto-created if omitted)
#   --ka-display-name   KA display name          (created if not found)
#   --app-path          Workspace path to app/ directory (required)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Step 1: Read all variable defaults from databricks.yml ───────────────────
# databricks.yml is the single source of truth — no defaults hardcoded here.
echo "Reading config from databricks.yml..."
_py=$(mktemp /tmp/yaml_parser_XXXXXX.py)
cat > "$_py" << 'PYEOF'
import re, sys

with open("databricks.yml") as f:
    content = f.read()

current_var = None
for line in content.splitlines():
    m = re.match(r'^  (\w+):', line)
    if m:
        current_var = m.group(1)
    if current_var:
        m2 = re.match(r'^\s+default:\s*["\']?(.*?)["\']?\s*$', line)
        if m2:
            val = m2.group(1).replace('"', '\\"')
            print('%s="%s"' % (current_var.upper(), val))
            current_var = None
PYEOF
_yaml_vars=$(python3 "$_py")
rm -f "$_py"
eval "$_yaml_vars"

# Deployment mechanics — not bundle variables, not in databricks.yml
PROFILE="DEFAULT"
APP_NAME="icd10-gap-advisor"
APP_SOURCE_PATH=""

# ── Command-line overrides ────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --profile)           PROFILE="$2";           shift 2 ;;
    --catalog)           CATALOG="$2";           shift 2 ;;
    --schema)            SCHEMA="$2";            shift 2 ;;
    --warehouse-id)      WAREHOUSE_ID="$2";      shift 2 ;;
    --ka-display-name)   KA_DISPLAY_NAME="$2";   shift 2 ;;
    --app-path)          APP_SOURCE_PATH="$2";   shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [ -z "$APP_SOURCE_PATH" ]; then
  echo "ERROR: --app-path is required."
  echo "  Example: --app-path /Workspace/Users/you@databricks.com/icd10-gapanalysis-demo/app"
  exit 1
fi

echo ""
echo "═══════════════════════════════════════════════════"
echo "  ICD-10 Gap Analysis Demo — Deployment"
echo "═══════════════════════════════════════════════════"
echo "  Profile:       $PROFILE"
echo "  Catalog:       $CATALOG / $SCHEMA"
echo "  App source:    $APP_SOURCE_PATH"
echo "  KA name:       $KA_DISPLAY_NAME"
echo "═══════════════════════════════════════════════════"
echo ""

# ── Step 2: Resolve SQL warehouse + KA endpoint ───────────────────────────────
echo "▶ Step 2/6 — Resolving SQL warehouse and KA endpoint"
_resource_vars=$(python3 "${SCRIPT_DIR}/setup_resources.py" \
    --profile          "$PROFILE" \
    --catalog          "$CATALOG" \
    --schema           "$SCHEMA" \
    --warehouse-id     "$WAREHOUSE_ID" \
    --ka-display-name  "$KA_DISPLAY_NAME")
eval "$_resource_vars"

echo "  Warehouse:   $WAREHOUSE_ID"
echo "  KA name:     $KA_DISPLAY_NAME"
echo "  KA endpoint: $KA_ENDPOINT_NAME"
echo "✔ Resources resolved"
echo ""

# ── Step 3: Generate app.yaml from resolved values ────────────────────────────
# All variables from databricks.yml are reflected as env vars in the app.
echo "▶ Step 3/6 — Generating app.yaml"
TEMP_APP_YAML="$(mktemp /tmp/icd10_app_yaml.XXXXXX)"

cat > "$TEMP_APP_YAML" << APPCFG
command: ["python", "app.py"]

# Generated by deploy.sh — do not edit manually.
# Source of truth: databricks.yml variables.

env:
  - name: UC_CATALOG
    value: "${CATALOG}"
  - name: UC_SCHEMA
    value: "${SCHEMA}"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "${WAREHOUSE_ID}"
  - name: FMAPI_ENDPOINT
    value: "${FMAPI_ENDPOINT}"
  - name: KA_ENDPOINT_NAME
    value: "${KA_ENDPOINT_NAME}"
  - name: KA_NAME
    value: "${KA_NAME}"
  - name: DATA_SETUP_JOB_NAME
    value: "${DATA_SETUP_JOB_NAME}"
  - name: AI_SETUP_JOB_NAME
    value: "${AI_SETUP_JOB_NAME}"

resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "${WAREHOUSE_ID}"
      permission: "CAN_USE"
APPCFG

databricks workspace import "${APP_SOURCE_PATH}/app.yaml" \
  --file "$TEMP_APP_YAML" \
  --format AUTO \
  --overwrite \
  --profile="$PROFILE"

rm -f "$TEMP_APP_YAML"
echo "✔ app.yaml generated and uploaded"
echo ""

# ── Step 4: Deploy the app ────────────────────────────────────────────────────
echo "▶ Step 4/6 — Deploying Databricks App"
databricks apps deploy "$APP_NAME" \
  --source-code-path "$APP_SOURCE_PATH" \
  --mode SNAPSHOT \
  --profile="$PROFILE"
echo "✔ App deployed"
echo ""

# ── Step 5: Read app SP + grant permissions ───────────────────────────────────
echo "▶ Step 5/6 — Granting permissions to app service principal"
APP_SP_CLIENT_ID=$(
  databricks apps get "$APP_NAME" --profile="$PROFILE" -o json \
  | python3 -c 'import sys, json; print(json.load(sys.stdin)["service_principal_client_id"])'
)
APP_SP_NAME=$(
  databricks apps get "$APP_NAME" --profile="$PROFILE" -o json \
  | python3 -c 'import sys, json; print(json.load(sys.stdin)["service_principal_name"])'
)
echo "  App SP: $APP_SP_NAME ($APP_SP_CLIENT_ID)"

databricks permissions update warehouses "$WAREHOUSE_ID" \
  --profile="$PROFILE" \
  --json "{\"access_control_list\": [{\"service_principal_name\": \"$APP_SP_CLIENT_ID\", \"permission_level\": \"CAN_USE\"}]}" \
  > /dev/null
echo "  ✔ Warehouse CAN_USE granted"

KA_ENDPOINT_ID=$(
  databricks serving-endpoints get "$KA_ENDPOINT_NAME" --profile="$PROFILE" -o json \
  | python3 -c 'import sys, json; print(json.load(sys.stdin)["id"])'
)
databricks permissions update serving-endpoints "$KA_ENDPOINT_ID" \
  --profile="$PROFILE" \
  --json "{\"access_control_list\": [{\"service_principal_name\": \"$APP_SP_CLIENT_ID\", \"permission_level\": \"CAN_QUERY\"}]}" \
  > /dev/null
echo "  ✔ KA serving endpoint CAN_QUERY granted ($KA_ENDPOINT_NAME)"

KA_ID="${KA_NAME#knowledge-assistants/}"
databricks permissions update knowledge-assistants "$KA_ID" \
  --profile="$PROFILE" \
  --json "{\"access_control_list\": [{\"service_principal_name\": \"$APP_SP_CLIENT_ID\", \"permission_level\": \"CAN_QUERY\"}]}" \
  > /dev/null
echo "  ✔ KA resource CAN_QUERY granted (knowledge-assistants/$KA_ID)"
echo "✔ Permissions granted"
echo ""

# ── Step 6: Bundle deploy (Jobs) ──────────────────────────────────────────────
# All variable values flow from databricks.yml defaults + step 2 resolution.
echo "▶ Step 6/6 — Deploying bundle (Jobs)"
DATABRICKS_TF_EXEC_PATH=$(which terraform) DATABRICKS_TF_VERSION=1.15.2 \
databricks bundle deploy \
  --var="catalog=$CATALOG" \
  --var="schema=$SCHEMA" \
  --var="warehouse_id=$WAREHOUSE_ID" \
  --var="fmapi_endpoint=$FMAPI_ENDPOINT" \
  --var="ka_endpoint_name=$KA_ENDPOINT_NAME" \
  --var="ka_name=$KA_NAME" \
  --var="data_setup_job_name=$DATA_SETUP_JOB_NAME" \
  --var="ai_setup_job_name=$AI_SETUP_JOB_NAME" \
  --var="app_service_principal=$APP_SP_CLIENT_ID" \
  --profile="$PROFILE"
echo "✔ Bundle deployed"
echo ""

echo "═══════════════════════════════════════════════════"
echo "  Deployment complete!"
echo ""
echo "  App:         $APP_NAME"
echo "  Warehouse:   $WAREHOUSE_ID"
echo "  KA endpoint: $KA_ENDPOINT_NAME"
echo "  Care Gap:    databricks-claude-sonnet-4-6 (FMAPI)"
echo ""
echo "  Next steps:"
echo "  1. Open the app → run Job 1 (Data Setup)"
echo "  2. Run Job 2 (Knowledge Assistant Setup) after Job 1 completes"
echo "═══════════════════════════════════════════════════"
